// tools/extract_map_mods.py によって自動生成されました (source: poe-db)
const mapModList = {
  "エリアには多数のトーテムが出現する": {
    "mod": "エリアには多数のトーテムが出現する",
    "engMod": "Area contains many Totems",
    "value": "",
    "type": "Prefix",
    "weight": 1000,
    "tier": 9,
    "engRegex": "ms$",
    "Regex": "数のト",
    "tradeStatIds": [
      "explicit.stat_1000591322"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "レアモンスターの数が(##)%増加する": {
    "mod": "レアモンスターの数が(##)%増加する",
    "engMod": "(##)% increased number of Rare Monsters",
    "value": "20-30",
    "type": "Prefix",
    "weight": 1000,
    "tier": 1,
    "engRegex": "nu",
    "Regex": "アモ.*数",
    "tradeStatIds": [
      "explicit.stat_3793155082"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "マジックモンスターの数が(##)%増加する": {
    "mod": "マジックモンスターの数が(##)%増加する",
    "engMod": "(##)% increased Magic Monsters",
    "value": "20-30",
    "type": "Suffix",
    "weight": 1000,
    "tier": 0,
    "engRegex": "d mag",
    "Regex": "マ.*増",
    "tradeStatIds": [
      "explicit.stat_3873704640"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアにはスケルトンが生息している": {
    "mod": "エリアにはスケルトンが生息している",
    "engMod": "Area is inhabited by Skeletons",
    "value": "",
    "type": "Prefix",
    "weight": 150,
    "tier": 4,
    "engRegex": "eto",
    "Regex": "スケ",
    "tradeStatIds": [
      "explicit.stat_45546355"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアにはゴートマンが生息している": {
    "mod": "エリアにはゴートマンが生息している",
    "engMod": "Area is inhabited by Goatmen",
    "value": "",
    "type": "Prefix",
    "weight": 150,
    "tier": 4,
    "engRegex": "goa",
    "Regex": "トマ",
    "tradeStatIds": [
      "explicit.stat_1813544255"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアにはシーウィッチとその幼体が生息している": {
    "mod": "エリアにはシーウィッチとその幼体が生息している",
    "engMod": "Area is inhabited by Sea Witches and their Spawn",
    "value": "",
    "type": "Prefix",
    "weight": 150,
    "tier": 4,
    "engRegex": "itc",
    "Regex": "ーウ",
    "tradeStatIds": [
      "explicit.stat_25085466"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアにはアンデッドが生息している": {
    "mod": "エリアにはアンデッドが生息している",
    "engMod": "Area is inhabited by Undead",
    "value": "",
    "type": "Prefix",
    "weight": 150,
    "tier": 4,
    "engRegex": "by un",
    "Regex": "デッ",
    "tradeStatIds": [
      "explicit.stat_808491979"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアには遠距離攻撃を行うモンスターが生息している": {
    "mod": "エリアには遠距離攻撃を行うモンスターが生息している",
    "engMod": "Area is inhabited by ranged monsters",
    "value": "",
    "type": "Prefix",
    "weight": 150,
    "tier": 4,
    "engRegex": "rang",
    "Regex": "離",
    "tradeStatIds": [
      "explicit.stat_645841425"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアには動物が生息している": {
    "mod": "エリアには動物が生息している",
    "engMod": "Area is inhabited by Animals",
    "value": "",
    "type": "Prefix",
    "weight": 150,
    "tier": 4,
    "engRegex": "nim",
    "Regex": "動物",
    "tradeStatIds": [
      "explicit.stat_4198346809"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 9,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアにはデーモンが生息している": {
    "mod": "エリアにはデーモンが生息している",
    "engMod": "Area is inhabited by Demons",
    "value": "",
    "type": "Prefix",
    "weight": 150,
    "tier": 4,
    "engRegex": "emons",
    "Regex": "デー",
    "tradeStatIds": [
      "explicit.stat_3916182167"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアにはヒューマノイドが生息している": {
    "mod": "エリアにはヒューマノイドが生息している",
    "engMod": "Area is inhabited by Humanoids",
    "value": "",
    "type": "Prefix",
    "weight": 150,
    "tier": 4,
    "engRegex": "hum",
    "Regex": "マノ",
    "tradeStatIds": [
      "explicit.stat_2651141461"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアにはソラリスの狂信者が出現する": {
    "mod": "エリアにはソラリスの狂信者が出現する",
    "engMod": "Area is inhabited by Solaris fanatics",
    "value": "",
    "type": "Prefix",
    "weight": 150,
    "tier": 4,
    "engRegex": "laris",
    "Regex": "ラリ",
    "tradeStatIds": [
      "explicit.stat_2457517302"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアにはルナリスの狂信者が出現する": {
    "mod": "エリアにはルナリスの狂信者が出現する",
    "engMod": "Area is inhabited by Lunaris fanatics",
    "value": "",
    "type": "Prefix",
    "weight": 150,
    "tier": 4,
    "engRegex": "unari",
    "Regex": "ナリ",
    "tradeStatIds": [
      "explicit.stat_3134632618"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアにはゴーストが出現する": {
    "mod": "エリアにはゴーストが出現する",
    "engMod": "Area is inhabited by Ghosts",
    "value": "",
    "type": "Prefix",
    "weight": 150,
    "tier": 4,
    "engRegex": "osts",
    "Regex": "ース",
    "tradeStatIds": [
      "explicit.stat_3516340048"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアにはキタヴァの崇拝者が出現する": {
    "mod": "エリアにはキタヴァの崇拝者が出現する",
    "engMod": "Area is inhabited by Cultists of Kitava",
    "value": "",
    "type": "Prefix",
    "weight": 150,
    "tier": 4,
    "engRegex": "cul",
    "Regex": "タヴ",
    "tradeStatIds": [
      "explicit.stat_4252630904"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 9,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアのモンスターの種類が増える": {
    "mod": "エリアのモンスターの種類が増える",
    "engMod": "Area has increased monster variety",
    "value": "",
    "type": "Prefix",
    "weight": 1000,
    "tier": 8,
    "engRegex": "ety",
    "Regex": "の種",
    "tradeStatIds": [
      "explicit.stat_3561450806"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターのスキルは追加で#回連鎖する": {
    "mod": "モンスターのスキルは追加で#回連鎖する",
    "engMod": "Monsters' skills Chain # additional times",
    "value": "2",
    "type": "Prefix",
    "weight": 1000,
    "tier": 380,
    "engRegex": "' s",
    "Regex": "連鎖す",
    "tradeStatIds": [
      "explicit.stat_3183973644"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 9,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターはヘックスプルーフを持つ": {
    "mod": "モンスターはヘックスプルーフを持つ",
    "engMod": "Monsters are Hexproof",
    "value": "",
    "type": "Prefix",
    "weight": 800,
    "tier": 150,
    "engRegex": "re he",
    "Regex": "フを持",
    "tradeStatIds": [
      "explicit.stat_4154059009"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 9,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターはヒット時に毒を付与する": {
    "mod": "モンスターはヒット時に毒を付与する",
    "engMod": "Monsters Poison on Hit",
    "value": "",
    "type": "Suffix",
    "weight": 1000,
    "tier": 390,
    "engRegex": "son o",
    "Regex": "に毒を",
    "tradeStatIds": [
      "explicit.stat_3350803563"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 9,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "プレイヤーは曝露を付与することができない": {
    "mod": "プレイヤーは曝露を付与することができない",
    "engMod": "Players cannot inflict Exposure",
    "value": "",
    "type": "Suffix",
    "weight": 1000,
    "tier": 150,
    "engRegex": "ot i",
    "Regex": "は曝",
    "tradeStatIds": [
      "explicit.stat_1026390635"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアには#体のユニークボスがいる": {
    "mod": "エリアには#体のユニークボスがいる",
    "engMod": "Area contains two Unique Bosses",
    "value": "2",
    "type": "Prefix",
    "weight": 1000,
    "tier": 90,
    "engRegex": "two",
    "Regex": "体の",
    "tradeStatIds": [
      "explicit.stat_799271621"
    ],
    "map_item_drop_quantity_+%": 19,
    "map_item_drop_rarity_+%": 11,
    "map_pack_size_+%": 7,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターはスタンを受けることがない|モンスターのライフが(##)%上昇する": {
    "mod": "モンスターはスタンを受けることがない|モンスターのライフが(##)%上昇する",
    "engMod": "Monsters cannot be Stunned|(##)% more Monster Life",
    "value": "|25-30",
    "type": "Prefix",
    "weight": 1000,
    "tier": 100,
    "engRegex": "r li",
    "Regex": "ンを受",
    "tradeStatIds": [
      "explicit.stat_1041951480",
      "explicit.stat_95249895"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターは投射物を追加で#個放つ": {
    "mod": "モンスターは投射物を追加で#個放つ",
    "engMod": "Monsters fire # additional Projectiles",
    "value": "2",
    "type": "Prefix",
    "weight": 1000,
    "tier": 440,
    "engRegex": "oj",
    "Regex": "放つ",
    "tradeStatIds": [
      "explicit.stat_1309819744"
    ],
    "map_item_drop_quantity_+%": 19,
    "map_item_drop_rarity_+%": 11,
    "map_pack_size_+%": 7,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターの効果範囲が#%増加する": {
    "mod": "モンスターの効果範囲が#%増加する",
    "engMod": "Monsters have #% increased Area of Effect",
    "value": "100",
    "type": "Suffix",
    "weight": 800,
    "tier": 400,
    "engRegex": "e \\\\d+% increased ar",
    "Regex": "ターの効",
    "tradeStatIds": [
      "explicit.stat_1708461270"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターのクリティカル率が(##)%増加する|モンスターのクリティカルダメージ倍率 +(##)%": {
    "mod": "モンスターのクリティカル率が(##)%増加する|モンスターのクリティカルダメージ倍率 +(##)%",
    "engMod": "Monsters have (##)% increased Critical Strike Chance|+(##)% to Monster Critical Strike Multiplier",
    "value": "360-400|41-45",
    "type": "Suffix",
    "weight": 800,
    "tier": 500,
    "engRegex": "e Mu",
    "Regex": "ジ倍",
    "tradeStatIds": [
      "explicit.stat_2753083623",
      "explicit.stat_57326096"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 9,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターの物理ダメージ軽減率 +#%": {
    "mod": "モンスターの物理ダメージ軽減率 +#%",
    "engMod": "+#% Monster Physical Damage Reduction",
    "value": "40",
    "type": "Prefix",
    "weight": 800,
    "tier": 150,
    "engRegex": "uct",
    "Regex": "ジ軽",
    "tradeStatIds": [
      "explicit.stat_839186746"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターのライフが(##)%上昇する": {
    "mod": "モンスターのライフが(##)%上昇する",
    "engMod": "(##)% more Monster Life",
    "value": "40-49",
    "type": "Prefix",
    "weight": 1000,
    "tier": 100,
    "engRegex": "r li",
    "Regex": "フが.*上",
    "tradeStatIds": [
      "explicit.stat_95249895"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターのダメージが(##)%増加する": {
    "mod": "モンスターのダメージが(##)%増加する",
    "engMod": "(##)% increased Monster Damage",
    "value": "22-25",
    "type": "Prefix",
    "weight": 1000,
    "tier": 370,
    "engRegex": "r damage$",
    "Regex": "ターのダ.*増",
    "tradeStatIds": [
      "explicit.stat_1890519597"
    ],
    "map_item_drop_quantity_+%": 19,
    "map_item_drop_rarity_+%": 11,
    "map_pack_size_+%": 7,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターは物理ダメージの(##)%を追加火ダメージとして与える": {
    "mod": "モンスターは物理ダメージの(##)%を追加火ダメージとして与える",
    "engMod": "Monsters deal (##)% extra Physical Damage as Fire",
    "value": "90-110",
    "type": "Prefix",
    "weight": 1000,
    "tier": 450,
    "engRegex": "fire$",
    "Regex": "加火",
    "tradeStatIds": [
      "explicit.stat_1497673356"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 9,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターは物理ダメージの(##)%を追加冷気ダメージとして与える": {
    "mod": "モンスターは物理ダメージの(##)%を追加冷気ダメージとして与える",
    "engMod": "Monsters deal (##)% extra Physical Damage as Cold",
    "value": "90-110",
    "type": "Prefix",
    "weight": 1000,
    "tier": 450,
    "engRegex": "old$",
    "Regex": "加冷",
    "tradeStatIds": [
      "explicit.stat_3448216135"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 9,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターは物理ダメージの(##)%を追加雷ダメージとして与える": {
    "mod": "モンスターは物理ダメージの(##)%を追加雷ダメージとして与える",
    "engMod": "Monsters deal (##)% extra Physical Damage as Lightning",
    "value": "90-110",
    "type": "Prefix",
    "weight": 1000,
    "tier": 450,
    "engRegex": "as l",
    "Regex": "加雷",
    "tradeStatIds": [
      "explicit.stat_3416853625"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 9,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターはその物理ダメージの(##)%を追加混沌ダメージとして獲得する|モンスターによるヒット時に衰弱を#秒間付与する": {
    "mod": "モンスターはその物理ダメージの(##)%を追加混沌ダメージとして獲得する|モンスターによるヒット時に衰弱を#秒間付与する",
    "engMod": "Monsters gain (##)% of their Physical Damage as Extra Chaos Damage|Monsters Inflict Withered for # seconds on Hit",
    "value": "31-35|2",
    "type": "Prefix",
    "weight": 500,
    "tier": 455,
    "engRegex": "hered",
    "Regex": "に衰",
    "tradeStatIds": [
      "explicit.stat_1840747977",
      "explicit.stat_3044826007"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 9,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターの移動スピードが(##)%増加する|モンスターのアタックスピードが(##)%増加する|モンスターのキャストスピードが(##)%増加する": {
    "mod": "モンスターの移動スピードが(##)%増加する|モンスターのアタックスピードが(##)%増加する|モンスターのキャストスピードが(##)%増加する",
    "engMod": "(##)% increased Monster Movement Speed|(##)% increased Monster Attack Speed|(##)% increased Monster Cast Speed",
    "value": "25-30|35-45|35-45",
    "type": "Prefix",
    "weight": 1000,
    "tier": 420,
    "engRegex": "r at",
    "Regex": "ーのキ",
    "tradeStatIds": [
      "explicit.stat_2306522833",
      "explicit.stat_1913583994",
      "explicit.stat_2488361432"
    ],
    "map_item_drop_quantity_+%": 19,
    "map_item_drop_rarity_+%": 11,
    "map_pack_size_+%": 7,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "レアモンスターは物理の棘を持ち#の物理ダメージを反射する": {
    "mod": "レアモンスターは物理の棘を持ち#の物理ダメージを反射する",
    "engMod": "Rare Monsters have [PhysicalThorns|Physical Thorns] reflecting # Physical Damage",
    "value": "800",
    "type": "Prefix",
    "weight": 600,
    "tier": 1000,
    "engRegex": "cal Th",
    "Regex": "理の棘",
    "tradeStatIds": [
      "explicit.stat_3278889477",
      ""
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "レアモンスターは元素の棘を持ち#の元素ダメージを反射する": {
    "mod": "レアモンスターは元素の棘を持ち#の元素ダメージを反射する",
    "engMod": "Rare Monsters have [ElementalThorns|Elemental Thorns] reflecting # Elemental Damage",
    "value": "1500",
    "type": "Prefix",
    "weight": 600,
    "tier": 1000,
    "engRegex": "tal Th",
    "Regex": "素の棘",
    "tradeStatIds": [
      "explicit.stat_3938822425",
      ""
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "全てのプレイヤーのライフとエナジーシールドの回復レートが#%低下する": {
    "mod": "全てのプレイヤーのライフとエナジーシールドの回復レートが#%低下する",
    "engMod": "Players have #% less Recovery Rate of Life and Energy Shield",
    "value": "60",
    "type": "Suffix",
    "weight": 750,
    "tier": 650,
    "engRegex": "s rec",
    "Regex": "復レ",
    "tradeStatIds": [
      "explicit.stat_4181072906"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 9,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアには燃焼領域がまだらに存在する": {
    "mod": "エリアには燃焼領域がまだらに存在する",
    "engMod": "Area has patches of Burning Ground",
    "value": "",
    "type": "Suffix",
    "weight": 250,
    "tier": 310,
    "engRegex": "f bur",
    "Regex": "は燃焼",
    "tradeStatIds": [
      "explicit.stat_133340941"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアには冷却領域がまだらに存在する": {
    "mod": "エリアには冷却領域がまだらに存在する",
    "engMod": "Area has patches of Chilled Ground",
    "value": "",
    "type": "Suffix",
    "weight": 250,
    "tier": 310,
    "engRegex": "hil",
    "Regex": "は冷却",
    "tradeStatIds": [
      "explicit.stat_349586058"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアには感電領域がまだらに存在し受けるダメージを#%増加させる": {
    "mod": "エリアには感電領域がまだらに存在し受けるダメージを#%増加させる",
    "engMod": "Area has patches of Shocked Ground which increase Damage taken by #%",
    "value": "50",
    "type": "Suffix",
    "weight": 250,
    "tier": 310,
    "engRegex": "ked",
    "Regex": "電領",
    "tradeStatIds": [
      "explicit.stat_3246076198"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアには冒涜領域がまだらに存在する": {
    "mod": "エリアには冒涜領域がまだらに存在する",
    "engMod": "Area has patches of desecrated ground",
    "value": "",
    "type": "Suffix",
    "weight": 250,
    "tier": 310,
    "engRegex": "s of d",
    "Regex": "は冒涜",
    "tradeStatIds": [
      "explicit.stat_3577222856"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "プレイヤーはエレメンタルウィークネスの呪いを受ける": {
    "mod": "プレイヤーはエレメンタルウィークネスの呪いを受ける",
    "engMod": "Players are Cursed with Elemental Weakness",
    "value": "",
    "type": "Suffix",
    "weight": 1000,
    "tier": 360,
    "engRegex": "h el",
    "Regex": "ルウ",
    "tradeStatIds": [
      "explicit.stat_558910024"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "プレイヤーはヴァルネラビリティの呪いを受ける": {
    "mod": "プレイヤーはヴァルネラビリティの呪いを受ける",
    "engMod": "Players are Cursed with Vulnerability",
    "value": "",
    "type": "Suffix",
    "weight": 1000,
    "tier": 360,
    "engRegex": "h vu",
    "Regex": "ネラ",
    "tradeStatIds": [
      "explicit.stat_1366534040"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "プレイヤーはエンフィーブルの呪いを受ける": {
    "mod": "プレイヤーはエンフィーブルの呪いを受ける",
    "engMod": "Players are Cursed with Enfeeble",
    "value": "",
    "type": "Suffix",
    "weight": 1000,
    "tier": 360,
    "engRegex": "eble$",
    "Regex": "ンフ",
    "tradeStatIds": [
      "explicit.stat_4103440490"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "プレイヤーはテンポラルチェーンの呪いを受ける": {
    "mod": "プレイヤーはテンポラルチェーンの呪いを受ける",
    "engMod": "Players are Cursed with Temporal Chains",
    "value": "",
    "type": "Suffix",
    "weight": 1000,
    "tier": 360,
    "engRegex": "h tem",
    "Regex": "ンポ",
    "tradeStatIds": [
      "explicit.stat_2326202293"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "全てのプレイヤーはライフ、マナおよびエナジーシールドを自動回復することができない": {
    "mod": "全てのプレイヤーはライフ、マナおよびエナジーシールドを自動回復することができない",
    "engMod": "Players cannot Regenerate Life, Mana or Energy Shield",
    "value": "",
    "type": "Suffix",
    "weight": 600,
    "tier": 700,
    "engRegex": "gen",
    "Regex": "動回",
    "tradeStatIds": [
      "explicit.stat_1910157106"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 9,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "プレイヤーの全ての耐性の最大値 -(##)%": {
    "mod": "プレイヤーの全ての耐性の最大値 -(##)%",
    "engMod": "Players have -(##)% to all maximum Resistances",
    "value": "9-12",
    "type": "Suffix",
    "weight": 1000,
    "tier": 980,
    "engRegex": "o al",
    "Regex": "性の最",
    "tradeStatIds": [
      "explicit.stat_3376488707"
    ],
    "map_item_drop_quantity_+%": 19,
    "map_item_drop_rarity_+%": 11,
    "map_pack_size_+%": 7,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "ユニークボスのダメージが#%増加する|ユニークボスのアタックスピードおよびキャストスピードが#%増加する": {
    "mod": "ユニークボスのダメージが#%増加する|ユニークボスのアタックスピードおよびキャストスピードが#%増加する",
    "engMod": "Unique Boss deals #% increased Damage|Unique Boss has #% increased Attack and Cast Speed",
    "value": "25|30",
    "type": "Prefix",
    "weight": 1000,
    "tier": 420,
    "engRegex": "d at",
    "Regex": "ユ.*ピ",
    "tradeStatIds": [
      "explicit.stat_124877078",
      "explicit.stat_2109106920"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 9,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "ユニークボスのライフが#%増加する|ユニークボスの効果範囲が#%増加する": {
    "mod": "ユニークボスのライフが#%増加する|ユニークボスの効果範囲が#%増加する",
    "engMod": "Unique Boss has #% increased Life|Unique Boss has #% increased Area of Effect",
    "value": "35|70",
    "type": "Prefix",
    "weight": 1000,
    "tier": 400,
    "engRegex": "d li",
    "Regex": "ユ.*範",
    "tradeStatIds": [
      "explicit.stat_1959158336",
      "explicit.stat_3040667106"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターからリーチできない": {
    "mod": "モンスターからリーチできない",
    "engMod": "Monsters cannot be Leeched from",
    "value": "",
    "type": "Suffix",
    "weight": 600,
    "tier": 600,
    "engRegex": "eche",
    "Regex": "ーチで",
    "tradeStatIds": [
      "explicit.stat_1140978125"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 9,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターは#%の確率で元素系状態異常を無効化する": {
    "mod": "モンスターは#%の確率で元素系状態異常を無効化する",
    "engMod": "Monsters have #% chance to Avoid Elemental Ailments",
    "value": "70",
    "type": "Suffix",
    "weight": 800,
    "tier": 150,
    "engRegex": "l Ai",
    "Regex": "系状",
    "tradeStatIds": [
      "explicit.stat_322206271"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターがクリティカルストライクから受ける追加ダメージが(##)%減少する": {
    "mod": "モンスターがクリティカルストライクから受ける追加ダメージが(##)%減少する",
    "engMod": "Monsters take (##)% reduced Extra Damage from Critical Strikes",
    "value": "36-40",
    "type": "Suffix",
    "weight": 800,
    "tier": 250,
    "engRegex": "kes",
    "Regex": "クか",
    "tradeStatIds": [
      "explicit.stat_337935900"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "全てのプレイヤーの獲得フラスコチャージが#%減少する": {
    "mod": "全てのプレイヤーの獲得フラスコチャージが#%減少する",
    "engMod": "Players gain #% reduced Flask Charges",
    "value": "50",
    "type": "Suffix",
    "weight": 800,
    "tier": 210,
    "engRegex": "ask",
    "Regex": "コチ",
    "tradeStatIds": [
      "explicit.stat_2549889921"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターに対する呪いの効果が#%低下する": {
    "mod": "モンスターに対する呪いの効果が#%低下する",
    "engMod": "#% less effect of Curses on Monsters",
    "value": "60",
    "type": "Prefix",
    "weight": 800,
    "tier": 363,
    "engRegex": "rses",
    "Regex": "いの効",
    "tradeStatIds": [
      "explicit.stat_3796523155"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターはヒット時に#%の確率で発火、凍結および感電を付与する": {
    "mod": "モンスターはヒット時に#%の確率で発火、凍結および感電を付与する",
    "engMod": "Monsters have a #% chance to Ignite, Freeze and Shock on Hit",
    "value": "20",
    "type": "Prefix",
    "weight": 800,
    "tier": 98,
    "engRegex": "te,",
    "Regex": "、凍",
    "tradeStatIds": [
      "explicit.stat_2553656203"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアにはアボミネーションが出現する": {
    "mod": "エリアにはアボミネーションが出現する",
    "engMod": "Area is inhabited by Abominations",
    "value": "",
    "type": "Prefix",
    "weight": 150,
    "tier": 4,
    "engRegex": "bom",
    "Regex": "ミネ",
    "tradeStatIds": [
      "explicit.stat_2961018200"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 9,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターのアクションスピードは基礎値よりも低く修正されることがない|モンスターの移動スピードは基礎値よりも低く修正されることがない|モンスターは挑発を受けることがない": {
    "mod": "モンスターのアクションスピードは基礎値よりも低く修正されることがない|モンスターの移動スピードは基礎値よりも低く修正されることがない|モンスターは挑発を受けることがない",
    "engMod": "Monsters' Action Speed cannot be modified to below Base Value|Monsters' Movement Speed cannot be modified to below Base Value|Monsters cannot be Taunted",
    "value": "||",
    "type": "Prefix",
    "weight": 650,
    "tier": 89,
    "engRegex": "elo",
    "Regex": "は挑",
    "tradeStatIds": [
      "explicit.stat_2758454849",
      "explicit.stat_777421120",
      "explicit.stat_1106651798"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターの全てのダメージにより発火が付与される": {
    "mod": "モンスターの全てのダメージにより発火が付与される",
    "engMod": "All Monster Damage from Hits always Ignites",
    "value": "",
    "type": "Prefix",
    "weight": 650,
    "tier": 99,
    "engRegex": "lw",
    "Regex": "り発",
    "tradeStatIds": [
      "explicit.stat_816367946"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターの混沌耐性 +#%|モンスターの元素耐性 +#%": {
    "mod": "モンスターの混沌耐性 +#%|モンスターの元素耐性 +#%",
    "engMod": "+#% Monster Chaos Resistance|+#% Monster Elemental Resistances",
    "value": "25|40",
    "type": "Prefix",
    "weight": 800,
    "tier": 100,
    "engRegex": "r el",
    "Regex": "ーの元",
    "tradeStatIds": [
      "explicit.stat_365540634",
      "explicit.stat_1054098949"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターは#%の確率で毒、串刺しおよび出血を無効化する": {
    "mod": "モンスターは#%の確率で毒、串刺しおよび出血を無効化する",
    "engMod": "Monsters have a #% chance to avoid Poison, Impale, and Bleeding",
    "value": "50",
    "type": "Prefix",
    "weight": 800,
    "tier": 390,
    "engRegex": "on,",
    "Regex": "で毒、",
    "tradeStatIds": [
      "explicit.stat_144665660"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "全てのプレイヤーのブロック率が#%減少する|全てのプレイヤーのアーマーが#%低下する": {
    "mod": "全てのプレイヤーのブロック率が#%減少する|全てのプレイヤーのアーマーが#%低下する",
    "engMod": "Players have #% reduced Chance to Block|Players have #% less Armour",
    "value": "40|30",
    "type": "Suffix",
    "weight": 800,
    "tier": 295,
    "engRegex": "ur$",
    "Regex": "ク率が",
    "tradeStatIds": [
      "explicit.stat_3729221884",
      "explicit.stat_272758639"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "全てのプレイヤーはスペルダメージを抑制して防ぐダメージ割合が#%される|モンスターの命中力が#%増加する": {
    "mod": "全てのプレイヤーはスペルダメージを抑制して防ぐダメージ割合が#%される|モンスターの命中力が#%増加する",
    "engMod": "Players have #% to amount of Suppressed Spell Damage Prevented|Monsters have #% increased Accuracy Rating",
    "value": "-20|50",
    "type": "Suffix",
    "weight": 800,
    "tier": 365,
    "engRegex": "prev",
    "Regex": "を抑",
    "tradeStatIds": [
      "explicit.stat_286947568",
      "explicit.stat_1588049749"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "全てのプレイヤーの効果範囲が#%低下する": {
    "mod": "全てのプレイヤーの効果範囲が#%低下する",
    "engMod": "Players have #% less Area of Effect",
    "value": "25",
    "type": "Suffix",
    "weight": 800,
    "tier": 60,
    "engRegex": "ss are",
    "Regex": "範.*低",
    "tradeStatIds": [
      "explicit.stat_2312028586"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターはヒット時にフレンジーチャージを#個獲得する": {
    "mod": "モンスターはヒット時にフレンジーチャージを#個獲得する",
    "engMod": "Monsters gain a Frenzy Charge on Hit",
    "value": "",
    "type": "Suffix",
    "weight": 800,
    "tier": 80,
    "engRegex": "mum f",
    "Regex": "にフレ",
    "tradeStatIds": [
      "explicit.stat_1742567045"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターはヒット時にエンデュランスチャージを#個獲得する": {
    "mod": "モンスターはヒット時にエンデュランスチャージを#個獲得する",
    "engMod": "Monsters gain an Endurance Charge on Hit",
    "value": "",
    "type": "Suffix",
    "weight": 800,
    "tier": 80,
    "engRegex": "e charge o",
    "Regex": "にエ",
    "tradeStatIds": [
      "explicit.stat_687813731"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターはヒット時にパワーチャージを#個獲得する": {
    "mod": "モンスターはヒット時にパワーチャージを#個獲得する",
    "engMod": "Monsters gain a Power Charge on Hit",
    "value": "",
    "type": "Suffix",
    "weight": 800,
    "tier": 80,
    "engRegex": "mum p",
    "Regex": "パ.*時",
    "tradeStatIds": [
      "explicit.stat_406353061"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターアタックはヒット時に#%の確率で串刺しを付与する": {
    "mod": "モンスターアタックはヒット時に#%の確率で串刺しを付与する",
    "engMod": "Monsters' Attacks have #% chance to Impale on Hit",
    "value": "60",
    "type": "Prefix",
    "weight": 800,
    "tier": 98,
    "engRegex": "' at",
    "Regex": "で串",
    "tradeStatIds": [
      "explicit.stat_1541224187"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 9,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターのスペルダメージ抑制確率 +#%": {
    "mod": "モンスターのスペルダメージ抑制確率 +#%",
    "engMod": "Monsters have +#% chance to Suppress Spell Damage",
    "value": "60",
    "type": "Prefix",
    "weight": 800,
    "tier": 290,
    "engRegex": "o su",
    "Regex": "ジ抑",
    "tradeStatIds": [
      "explicit.stat_2138205941"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターは最大ライフの(##)%を追加最大エナジーシールドとして獲得する": {
    "mod": "モンスターは最大ライフの(##)%を追加最大エナジーシールドとして獲得する",
    "engMod": "Monsters gain (##)% of Maximum Life as Extra Maximum Energy Shield",
    "value": "40-49",
    "type": "Prefix",
    "weight": 800,
    "tier": 240,
    "engRegex": "m li",
    "Regex": "加最",
    "tradeStatIds": [
      "explicit.stat_2887760183"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "ユニークボスは取り憑かれている": {
    "mod": "ユニークボスは取り憑かれている",
    "engMod": "Unique Bosses are Possessed",
    "value": "",
    "type": "Prefix",
    "weight": 1000,
    "tier": 90,
    "engRegex": "poss",
    "Regex": "り憑",
    "tradeStatIds": [
      "explicit.stat_2588474575"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 9,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターはヒット時に盲目を付与する": {
    "mod": "モンスターはヒット時に盲目を付与する",
    "engMod": "Monsters Blind on Hit",
    "value": "",
    "type": "Suffix",
    "weight": 650,
    "tier": 50,
    "engRegex": "s bli",
    "Regex": "に盲",
    "tradeStatIds": [
      "explicit.stat_1629869774"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターはアタックによるヒット時に重傷を付与する": {
    "mod": "モンスターはアタックによるヒット時に重傷を付与する",
    "engMod": "Monsters Maim on Hit with Attacks",
    "value": "",
    "type": "Suffix",
    "weight": 600,
    "tier": 50,
    "engRegex": "aim",
    "Regex": "に重",
    "tradeStatIds": [
      "explicit.stat_4164174520"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターはスペルによるヒット時に阻害を付与する": {
    "mod": "モンスターはスペルによるヒット時に阻害を付与する",
    "engMod": "Monsters Hinder on Hit with Spells",
    "value": "",
    "type": "Suffix",
    "weight": 600,
    "tier": 50,
    "engRegex": "hind",
    "Regex": "に阻",
    "tradeStatIds": [
      "explicit.stat_962720646"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "モンスターはヒット時にパワーチャージ、フレンジーチャージおよびエンデュランスチャージのスタックを盗む": {
    "mod": "モンスターはヒット時にパワーチャージ、フレンジーチャージおよびエンデュランスチャージのスタックを盗む",
    "engMod": "Monsters steal Power, Frenzy and Endurance charges on Hit",
    "value": "",
    "type": "Suffix",
    "weight": 800,
    "tier": 80,
    "engRegex": "er,",
    "Regex": "盗む",
    "tradeStatIds": [
      "explicit.stat_3222482040"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "エリアにはまだら状に神聖領域がある": {
    "mod": "エリアにはまだら状に神聖領域がある",
    "engMod": "Area has patches of Consecrated Ground",
    "value": "",
    "type": "Suffix",
    "weight": 250,
    "tier": 310,
    "engRegex": "nsecrate",
    "Regex": "状に神",
    "tradeStatIds": [
      "explicit.stat_1948962470"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "全てのプレイヤーのクールダウン解消レートが#%低下する": {
    "mod": "全てのプレイヤーのクールダウン解消レートが#%低下する",
    "engMod": "Players have #% less Cooldown Recovery Rate",
    "value": "40",
    "type": "Suffix",
    "weight": 650,
    "tier": 94,
    "engRegex": "coo",
    "Regex": "ン解",
    "tradeStatIds": [
      "explicit.stat_941368244"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "全てのプレイヤーに対するバフは#%速く消える": {
    "mod": "全てのプレイヤーに対するバフは#%速く消える",
    "engMod": "Buffs on Players expire #% faster",
    "value": "70",
    "type": "Suffix",
    "weight": 650,
    "tier": 96,
    "engRegex": "fs",
    "Regex": "イ.*速",
    "tradeStatIds": [
      "explicit.stat_1217583941"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "全てのプレイヤーはスキルによる呪い以外のオーラの効果が#%減少する": {
    "mod": "全てのプレイヤーはスキルによる呪い以外のオーラの効果が#%減少する",
    "engMod": "Players have #% reduced effect of Non-Curse Auras from Skills",
    "value": "60",
    "type": "Suffix",
    "weight": 800,
    "tier": 990,
    "engRegex": "non",
    "Regex": "ラの",
    "tradeStatIds": [
      "explicit.stat_2450628570"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "全てのプレイヤーの命中力が#%低下する": {
    "mod": "全てのプレイヤーの命中力が#%低下する",
    "engMod": "Players have #% less Accuracy Rating",
    "value": "25",
    "type": "Suffix",
    "weight": 800,
    "tier": 85,
    "engRegex": "s ac",
    "Regex": "命.*低",
    "tradeStatIds": [
      "explicit.stat_3667574329"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": false
  },
  "(T17) モンスターのスキルは追加で#回連鎖する|モンスターの投射物は地形と衝突した時に連鎖することができる": {
    "mod": "(T17) モンスターのスキルは追加で#回連鎖する|モンスターの投射物は地形と衝突した時に連鎖することができる",
    "engMod": "(T17) Monsters' skills Chain # additional times|Monsters' Projectiles can Chain when colliding with Terrain",
    "value": "3|",
    "type": "Prefix",
    "weight": 50,
    "tier": 1639,
    "engRegex": "lid",
    "Regex": "に連",
    "tradeStatIds": [
      "explicit.stat_3183973644",
      "explicit.stat_2753403220"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 56,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターはヒット時にパワーチャージを#個獲得する|モンスターの最大パワーチャージ数が+#される": {
    "mod": "(T17) モンスターはヒット時にパワーチャージを#個獲得する|モンスターの最大パワーチャージ数が+#される",
    "engMod": "(T17) Monsters gain a Power Charge on Hit|Monsters have +# to Maximum Power Charges",
    "value": "|1",
    "type": "Suffix",
    "weight": 100,
    "tier": 1287,
    "engRegex": "mum p",
    "Regex": "パ.*時",
    "tradeStatIds": [
      "explicit.stat_406353061",
      "explicit.stat_1103106414"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 35,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターはヒット時にフレンジーチャージを#個獲得する|モンスターの最大フレンジーチャージ数が+#される": {
    "mod": "(T17) モンスターはヒット時にフレンジーチャージを#個獲得する|モンスターの最大フレンジーチャージ数が+#される",
    "engMod": "(T17) Monsters gain a Frenzy Charge on Hit|Monsters have +# to Maximum Frenzy Charges",
    "value": "|1",
    "type": "Suffix",
    "weight": 100,
    "tier": 1288,
    "engRegex": "mum f",
    "Regex": "大フ",
    "tradeStatIds": [
      "explicit.stat_1742567045",
      "explicit.stat_3900284865"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 35,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターの最大エンデュランスチャージ数が+#される|モンスターはヒットを受けた時にエンデュランスチャージを#個獲得する": {
    "mod": "(T17) モンスターの最大エンデュランスチャージ数が+#される|モンスターはヒットを受けた時にエンデュランスチャージを#個獲得する",
    "engMod": "(T17) Monsters have +# to Maximum Endurance Charges|Monsters gain an Endurance Charge when hit",
    "value": "1|",
    "type": "Suffix",
    "weight": 100,
    "tier": 1209,
    "engRegex": "m end",
    "Regex": "にエ",
    "tradeStatIds": [
      "explicit.stat_4067268731",
      "explicit.stat_3707756896"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 35,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) プレイヤーの全ての耐性の最大値 #%": {
    "mod": "(T17) プレイヤーの全ての耐性の最大値 #%",
    "engMod": "(T17) Players have #% to all maximum Resistances",
    "value": "-20",
    "type": "Suffix",
    "weight": 50,
    "tier": 1111,
    "engRegex": "o al",
    "Regex": "値 -2",
    "tradeStatIds": [
      "explicit.stat_3376488707"
    ],
    "map_item_drop_quantity_+%": 19,
    "map_item_drop_rarity_+%": 11,
    "map_pack_size_+%": 20,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターは投射物を追加で#個放つ|モンスターの効果範囲が#%増加する": {
    "mod": "(T17) モンスターは投射物を追加で#個放つ|モンスターの効果範囲が#%増加する",
    "engMod": "(T17) Monsters fire # additional Projectiles|Monsters have #% increased Area of Effect",
    "value": "2|100",
    "type": "Prefix",
    "weight": 100,
    "tier": 1644,
    "engRegex": "tiles$",
    "Regex": "ターの効",
    "tradeStatIds": [
      "explicit.stat_1309819744",
      "explicit.stat_1708461270"
    ],
    "map_item_drop_quantity_+%": 19,
    "map_item_drop_rarity_+%": 56,
    "map_pack_size_+%": 7,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターのクリティカルダメージ倍率 +(##)%|モンスターのクリティカル率が(##)%増加する": {
    "mod": "(T17) モンスターのクリティカルダメージ倍率 +(##)%|モンスターのクリティカル率が(##)%増加する",
    "engMod": "(T17) +(##)% to Monster Critical Strike Multiplier|Monsters have (##)% increased Critical Strike Chance",
    "value": "70-75|650-700",
    "type": "Suffix",
    "weight": 100,
    "tier": 1111,
    "engRegex": "lier",
    "Regex": "ジ倍",
    "tradeStatIds": [
      "explicit.stat_57326096",
      "explicit.stat_2753083623"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 56,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターはヒット時に毒を付与する|モンスターによる毒の持続時間が#%増加する|モンスターによる全てのダメージが毒を付与できる": {
    "mod": "(T17) モンスターはヒット時に毒を付与する|モンスターによる毒の持続時間が#%増加する|モンスターによる全てのダメージが毒を付与できる",
    "engMod": "(T17) Monsters Poison on Hit|Monsters have #% increased Poison Duration|All Damage from Monsters' Hits can Poison",
    "value": "|100|",
    "type": "Suffix",
    "weight": 50,
    "tier": 1605,
    "engRegex": "son$",
    "Regex": "に毒を",
    "tradeStatIds": [
      "explicit.stat_3350803563",
      "explicit.stat_134839587",
      "explicit.stat_3555807120"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 49,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターのダメージが(##)%増加する": {
    "mod": "(T17) モンスターのダメージが(##)%増加する",
    "engMod": "(T17) (##)% increased Monster Damage",
    "value": "30-40",
    "type": "Prefix",
    "weight": 1000,
    "tier": 370,
    "engRegex": "r damage$",
    "Regex": "ターのダ.*増",
    "tradeStatIds": [
      "explicit.stat_1890519597"
    ],
    "map_item_drop_quantity_+%": 19,
    "map_item_drop_rarity_+%": 56,
    "map_pack_size_+%": 7,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターは最大ライフの(##)%を追加最大エナジーシールドとして獲得する": {
    "mod": "(T17) モンスターは最大ライフの(##)%を追加最大エナジーシールドとして獲得する",
    "engMod": "(T17) Monsters gain (##)% of Maximum Life as Extra Maximum Energy Shield",
    "value": "70-80",
    "type": "Prefix",
    "weight": 800,
    "tier": 240,
    "engRegex": "m li",
    "Regex": "加最",
    "tradeStatIds": [
      "explicit.stat_2887760183"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 35,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) ユニークボスは取り憑かれている": {
    "mod": "(T17) ユニークボスは取り憑かれている",
    "engMod": "(T17) Unique Bosses are Possessed",
    "value": "",
    "type": "Prefix",
    "weight": 1000,
    "tier": 90,
    "engRegex": "poss",
    "Regex": "り憑",
    "tradeStatIds": [
      "explicit.stat_2588474575"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 56,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターのスペルダメージ抑制確率 +#%": {
    "mod": "(T17) モンスターのスペルダメージ抑制確率 +#%",
    "engMod": "(T17) Monsters have +#% chance to Suppress Spell Damage",
    "value": "100",
    "type": "Prefix",
    "weight": 800,
    "tier": 290,
    "engRegex": "o su",
    "Regex": "ジ抑",
    "tradeStatIds": [
      "explicit.stat_2138205941"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 35,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターのアタックダメージブロック確率 +#%": {
    "mod": "(T17) モンスターのアタックダメージブロック確率 +#%",
    "engMod": "(T17) Monsters have +#% Chance to Block Attack Damage",
    "value": "50",
    "type": "Prefix",
    "weight": 60,
    "tier": 1303,
    "engRegex": "k at",
    "Regex": "ジブ",
    "tradeStatIds": [
      "explicit.stat_881836292"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 47,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) プレイヤーはリーチによるライフ、マナおよびエナジーシールドの最大合計回復量が(##)%減少する": {
    "mod": "(T17) プレイヤーはリーチによるライフ、マナおよびエナジーシールドの最大合計回復量が(##)%減少する",
    "engMod": "(T17) Players have (##)% reduced Maximum total Life, Mana and Energy Shield Recovery per second from Leech",
    "value": "50-60",
    "type": "Suffix",
    "weight": 30,
    "tier": 1190,
    "engRegex": "tota",
    "Regex": "チによ",
    "tradeStatIds": [
      "explicit.stat_2946888410"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 49,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) レアモンスターは物理の棘を持ち#の物理ダメージを反射する|レアモンスターは元素の棘を持ち#の元素ダメージを反射する": {
    "mod": "(T17) レアモンスターは物理の棘を持ち#の物理ダメージを反射する|レアモンスターは元素の棘を持ち#の元素ダメージを反射する",
    "engMod": "(T17) Rare Monsters have [PhysicalThorns|Physical Thorns] reflecting # Physical Damage|Rare Monsters have [ElementalThorns|Elemental Thorns] reflecting # Elemental Damage",
    "value": "1500|2500",
    "type": "Prefix",
    "weight": 40,
    "tier": 2202,
    "engRegex": "orns ref",
    "Regex": "の棘を持",
    "tradeStatIds": [
      "explicit.stat_3278889477",
      "explicit.stat_3938822425",
      "",
      ""
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 47,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) プレイヤーはヴァルネラビリティの呪いを受ける|プレイヤーはテンポラルチェーンの呪いを受ける|プレイヤーはエレメンタルウィークネスの呪いを受ける": {
    "mod": "(T17) プレイヤーはヴァルネラビリティの呪いを受ける|プレイヤーはテンポラルチェーンの呪いを受ける|プレイヤーはエレメンタルウィークネスの呪いを受ける",
    "engMod": "(T17) Players are Cursed with Vulnerability|Players are Cursed with Temporal Chains|Players are Cursed with Elemental Weakness",
    "value": "||",
    "type": "Suffix",
    "weight": 60,
    "tier": 1556,
    "engRegex": "vu",
    "Regex": "ネラ",
    "tradeStatIds": [
      "explicit.stat_1366534040",
      "explicit.stat_2326202293",
      "explicit.stat_558910024"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 11,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 35,
    "modTier17": true
  },
  "(T17) 全てのプレイヤーの効果範囲が(##)%低下する": {
    "mod": "(T17) 全てのプレイヤーの効果範囲が(##)%低下する",
    "engMod": "(T17) Players have (##)% less Area of Effect",
    "value": "25-30",
    "type": "Suffix",
    "weight": 800,
    "tier": 60,
    "engRegex": "ss are",
    "Regex": "範.*低",
    "tradeStatIds": [
      "explicit.stat_2312028586"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 69,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターがクリティカルストライクから受ける追加ダメージが(##)%減少する": {
    "mod": "(T17) モンスターがクリティカルストライクから受ける追加ダメージが(##)%減少する",
    "engMod": "(T17) Monsters take (##)% reduced Extra Damage from Critical Strikes",
    "value": "35-45",
    "type": "Suffix",
    "weight": 800,
    "tier": 250,
    "engRegex": "kes",
    "Regex": "クか",
    "tradeStatIds": [
      "explicit.stat_337935900"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 56,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターのライフが(##)%上昇する": {
    "mod": "(T17) モンスターのライフが(##)%上昇する",
    "engMod": "(T17) (##)% more Monster Life",
    "value": "90-100",
    "type": "Prefix",
    "weight": 1000,
    "tier": 100,
    "engRegex": "r li",
    "Regex": "フが.*上",
    "tradeStatIds": [
      "explicit.stat_95249895"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 47,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) それぞれのレアモンスターはモッドを追加で#個持つ|レアモンスターの数が(##)%増加する": {
    "mod": "(T17) それぞれのレアモンスターはモッドを追加で#個持つ|レアモンスターの数が(##)%増加する",
    "engMod": "(T17) Rare Monsters each have # additional Modifier|(##)% increased number of Rare Monsters",
    "value": "1|35-45",
    "type": "Prefix",
    "weight": 30,
    "tier": 1231,
    "engRegex": "fier$",
    "Regex": "はモ",
    "tradeStatIds": [
      "explicit.stat_2550456553",
      "explicit.stat_3793155082"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) ユニークモンスターはランダムなシュラインバフを#個持つ": {
    "mod": "(T17) ユニークモンスターはランダムなシュラインバフを#個持つ",
    "engMod": "(T17) Unique Monsters have a random Shrine Buff",
    "value": "",
    "type": "Suffix",
    "weight": 50,
    "tier": 1277,
    "engRegex": "ff$",
    "Regex": "フを",
    "tradeStatIds": [
      "explicit.stat_872972810"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 35,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターはヒット時に束縛する蔓を#スタック付与する": {
    "mod": "(T17) モンスターはヒット時に束縛する蔓を#スタック付与する",
    "engMod": "(T17) Monsters inflict # Grasping Vines on Hit",
    "value": "2",
    "type": "Prefix",
    "weight": 50,
    "tier": 1203,
    "engRegex": "pin",
    "Regex": "に束",
    "tradeStatIds": [
      "explicit.stat_1751584857"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 40,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) レアモンスターはボラタイルコアを持つ": {
    "mod": "(T17) レアモンスターはボラタイルコアを持つ",
    "engMod": "(T17) Rare Monsters have Volatile Cores",
    "value": "",
    "type": "Prefix",
    "weight": 50,
    "tier": 1186,
    "engRegex": "vola",
    "Regex": "ラタ",
    "tradeStatIds": [
      "explicit.stat_1706239920"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 11,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 53,
    "modTier17": true
  },
  "(T17) モンスターはその物理ダメージの(##)%をランダムな元素属性の追加ダメージとして獲得する": {
    "mod": "(T17) モンスターはその物理ダメージの(##)%をランダムな元素属性の追加ダメージとして獲得する",
    "engMod": "(T17) Monsters gain (##)% of their Physical Damage as Extra Damage of a random Element",
    "value": "180-200",
    "type": "Prefix",
    "weight": 100,
    "tier": 1663,
    "engRegex": "ment$",
    "Regex": "な元",
    "tradeStatIds": [
      "explicit.stat_4062840317"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 71,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターはその物理ダメージの(##)%を追加混沌ダメージとして獲得する": {
    "mod": "(T17) モンスターはその物理ダメージの(##)%を追加混沌ダメージとして獲得する",
    "engMod": "(T17) Monsters gain (##)% of their Physical Damage as Extra Chaos Damage",
    "value": "80-100",
    "type": "Prefix",
    "weight": 50,
    "tier": 1666,
    "engRegex": "ra c",
    "Regex": "沌ダ",
    "tradeStatIds": [
      "explicit.stat_1840747977"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 46,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターのキャストスピードが(##)%増加する|モンスターのアタックスピードが(##)%増加する|モンスターの移動スピードが(##)%増加する": {
    "mod": "(T17) モンスターのキャストスピードが(##)%増加する|モンスターのアタックスピードが(##)%増加する|モンスターの移動スピードが(##)%増加する",
    "engMod": "(T17) (##)% increased Monster Cast Speed|(##)% increased Monster Attack Speed|(##)% increased Monster Movement Speed",
    "value": "35-45|35-45|25-30",
    "type": "Prefix",
    "weight": 100,
    "tier": 1110,
    "engRegex": "r at",
    "Regex": "ーのキ",
    "tradeStatIds": [
      "explicit.stat_2488361432",
      "explicit.stat_1913583994",
      "explicit.stat_2306522833"
    ],
    "map_item_drop_quantity_+%": 19,
    "map_item_drop_rarity_+%": 56,
    "map_pack_size_+%": 7,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) プレイヤーは血塗れのノコギリに襲われる": {
    "mod": "(T17) プレイヤーは血塗れのノコギリに襲われる",
    "engMod": "(T17) Players are assaulted by Bloodstained Sawblades",
    "value": "",
    "type": "Prefix",
    "weight": 50,
    "tier": 1194,
    "engRegex": "wb",
    "Regex": "血塗",
    "tradeStatIds": [
      "explicit.stat_3052102815"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 47,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターはスタンを受けることがない|モンスターのアクションスピードは基礎値よりも低く修正されることがない|モンスターの移動スピードは基礎値よりも低く修正されることがない": {
    "mod": "(T17) モンスターはスタンを受けることがない|モンスターのアクションスピードは基礎値よりも低く修正されることがない|モンスターの移動スピードは基礎値よりも低く修正されることがない",
    "engMod": "(T17) Monsters cannot be Stunned|Monsters' Action Speed cannot be modified to below Base Value|Monsters' Movement Speed cannot be modified to below Base Value",
    "value": "||",
    "type": "Suffix",
    "weight": 40,
    "tier": 1314,
    "engRegex": "tun",
    "Regex": "礎値",
    "tradeStatIds": [
      "explicit.stat_1041951480",
      "explicit.stat_2758454849",
      "explicit.stat_777421120"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 47,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) プレイヤーはフラスコを使用した時に隕石の対象となる": {
    "mod": "(T17) プレイヤーはフラスコを使用した時に隕石の対象となる",
    "engMod": "(T17) Players are targeted by a Meteor when they use a Flask",
    "value": "",
    "type": "Suffix",
    "weight": 50,
    "tier": 1403,
    "engRegex": "get",
    "Regex": "に隕",
    "tradeStatIds": [
      "explicit.stat_4102870672"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 45,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) プレイヤーの防御力が(##)%低下する": {
    "mod": "(T17) プレイヤーの防御力が(##)%低下する",
    "engMod": "(T17) Players have (##)% less Defences",
    "value": "25-30",
    "type": "Suffix",
    "weight": 60,
    "tier": 1191,
    "engRegex": "efe",
    "Regex": "御力",
    "tradeStatIds": [
      "explicit.stat_943960754"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 35,
    "modTier17": true
  },
  "(T17) エリアには溺死のオーブが出現する": {
    "mod": "(T17) エリアには溺死のオーブが出現する",
    "engMod": "(T17) Area contains Drowning Orbs",
    "value": "",
    "type": "Prefix",
    "weight": 50,
    "tier": 1224,
    "engRegex": "wni",
    "Regex": "は溺",
    "tradeStatIds": [
      "explicit.stat_25225034"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 20,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターの物理ダメージ軽減率 +#%|モンスターの元素耐性 +#%|モンスターの混沌耐性 +#%": {
    "mod": "(T17) モンスターの物理ダメージ軽減率 +#%|モンスターの元素耐性 +#%|モンスターの混沌耐性 +#%",
    "engMod": "(T17) +#% Monster Physical Damage Reduction|+#% Monster Elemental Resistances|+#% Monster Chaos Resistance",
    "value": "50|55|35",
    "type": "Prefix",
    "weight": 100,
    "tier": 1378,
    "engRegex": "uct",
    "Regex": "ジ軽",
    "tradeStatIds": [
      "explicit.stat_839186746",
      "explicit.stat_1054098949",
      "explicit.stat_365540634"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 35,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターはヒット時に確率で発火、凍結および感電を付与する|モンスターは全てのダメージで発火、凍結および感電を付与できる": {
    "mod": "(T17) モンスターはヒット時に確率で発火、凍結および感電を付与する|モンスターは全てのダメージで発火、凍結および感電を付与できる",
    "engMod": "(T17) Monsters Ignite, Freeze and Shock on Hit|All Monster Damage can Ignite, Freeze and Shock",
    "value": "|",
    "type": "Prefix",
    "weight": 50,
    "tier": 1225,
    "engRegex": "hock$",
    "Regex": "、凍",
    "tradeStatIds": [
      "explicit.stat_2553656203",
      "explicit.stat_2919181457"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 60,
    "modTier17": true
  },
  "(T17) 全てのプレイヤーに対するバフは#%速く消える": {
    "mod": "(T17) 全てのプレイヤーに対するバフは#%速く消える",
    "engMod": "(T17) Buffs on Players expire #% faster",
    "value": "100",
    "type": "Suffix",
    "weight": 650,
    "tier": 96,
    "engRegex": "fs",
    "Regex": "イ.*速",
    "tradeStatIds": [
      "explicit.stat_1217583941"
    ],
    "map_item_drop_quantity_+%": 10,
    "map_item_drop_rarity_+%": 6,
    "map_pack_size_+%": 4,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 35,
    "modTier17": true
  },
  "(T17) モンスターのダメージは#%の元素耐性を貫通する": {
    "mod": "(T17) モンスターのダメージは#%の元素耐性を貫通する",
    "engMod": "(T17) Monster Damage Penetrates #% Elemental Resistances",
    "value": "15",
    "type": "Suffix",
    "weight": 50,
    "tier": 1216,
    "engRegex": "net",
    "Regex": "通す",
    "tradeStatIds": [
      "explicit.stat_1898978455"
    ],
    "map_item_drop_quantity_+%": 19,
    "map_item_drop_rarity_+%": 72,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) エリアには不安定な触手の悪魔が出現する": {
    "mod": "(T17) エリアには不安定な触手の悪魔が出現する",
    "engMod": "(T17) Area contains Unstable Tentacle Fiends",
    "value": "",
    "type": "Suffix",
    "weight": 50,
    "tier": 1221,
    "engRegex": "acl",
    "Regex": "な触",
    "tradeStatIds": [
      "explicit.stat_1943574423"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 11,
    "map_pack_size_+%": 20,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) エリアのレアモンスターはシェイパーに触れられている": {
    "mod": "(T17) エリアのレアモンスターはシェイパーに触れられている",
    "engMod": "(T17) Rare monsters in area are Shaper-Touched",
    "value": "",
    "type": "Prefix",
    "weight": 50,
    "tier": 1184,
    "engRegex": "hap",
    "Regex": "パーに触",
    "tradeStatIds": [
      "explicit.stat_2931889194"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 11,
    "map_pack_size_+%": 20,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) マップボスはシンセシスボスを伴う": {
    "mod": "(T17) マップボスはシンセシスボスを伴う",
    "engMod": "(T17) Map Boss is accompanied by a Synthesis Boss",
    "value": "",
    "type": "Prefix",
    "weight": 50,
    "tier": 1217,
    "engRegex": "yn",
    "Regex": "スボ",
    "tradeStatIds": [
      "explicit.stat_4150353141"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 20,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) モンスターに対するデバフは#%速く消える": {
    "mod": "(T17) モンスターに対するデバフは#%速く消える",
    "engMod": "(T17) Debuffs on Monsters expire #% faster",
    "value": "100",
    "type": "Suffix",
    "weight": 40,
    "tier": 1314,
    "engRegex": "deb",
    "Regex": "ス.*速",
    "tradeStatIds": [
      "explicit.stat_1200027417"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 12,
    "map_pack_size_+%": 6,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 64,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) エリアにはシアリング・エグザークのルーンが出現する": {
    "mod": "(T17) エリアにはシアリング・エグザークのルーンが出現する",
    "engMod": "(T17) Area contains Runes of the Searing Exarch",
    "value": "",
    "type": "Prefix",
    "weight": 50,
    "tier": 1222,
    "engRegex": "earing Ex",
    "Regex": "エグザークのル",
    "tradeStatIds": [
      "explicit.stat_2073168229"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 20,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) メイヴェンはプレイヤーに干渉する": {
    "mod": "(T17) メイヴェンはプレイヤーに干渉する",
    "engMod": "(T17) The Maven interferes with Players",
    "value": "",
    "type": "Suffix",
    "weight": 50,
    "tier": 1183,
    "engRegex": "mav",
    "Regex": "干渉す",
    "tradeStatIds": [
      "explicit.stat_1594156261"
    ],
    "map_item_drop_quantity_+%": 13,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 20,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) #%の確率でレアモンスターは死亡時にフラクチャー化する": {
    "mod": "(T17) #%の確率でレアモンスターは死亡時にフラクチャー化する",
    "engMod": "(T17) #% chance for Rare Monsters to Fracture on death",
    "value": "25",
    "type": "Suffix",
    "weight": 30,
    "tier": 1226,
    "engRegex": "fra",
    "Regex": "亡時",
    "tradeStatIds": [
      "explicit.stat_3097694855"
    ],
    "map_item_drop_quantity_+%": 19,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) 味方に影響する、プレイヤースキルによるオーラは敵にも影響する": {
    "mod": "(T17) 味方に影響する、プレイヤースキルによるオーラは敵にも影響する",
    "engMod": "(T17) Auras from Player Skills which affect Allies also affect Enemies",
    "value": "",
    "type": "Suffix",
    "weight": 50,
    "tier": 2201,
    "engRegex": "^au",
    "Regex": "ラは敵",
    "tradeStatIds": [
      "explicit.stat_2156372077"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 54,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) エリアのレアモンスターは死亡時に一時的に生き返る": {
    "mod": "(T17) エリアのレアモンスターは死亡時に一時的に生き返る",
    "engMod": "(T17) Rare monsters in area Temporarily Revive on death",
    "value": "",
    "type": "Suffix",
    "weight": 50,
    "tier": 1190,
    "engRegex": "ril",
    "Regex": "的に生",
    "tradeStatIds": [
      "explicit.stat_1593763475"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 17,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) エリアにはラビリンスの罠が出現する": {
    "mod": "(T17) エリアにはラビリンスの罠が出現する",
    "engMod": "(T17) Area contains Labyrinth Hazards",
    "value": "",
    "type": "Prefix",
    "weight": 50,
    "tier": 1190,
    "engRegex": "byr",
    "Regex": "の罠",
    "tradeStatIds": [
      "explicit.stat_2577650864"
    ],
    "map_item_drop_quantity_+%": 19,
    "map_item_drop_rarity_+%": 54,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) プレイヤーは適用されるフラスコの効果が#%低下する": {
    "mod": "(T17) プレイヤーは適用されるフラスコの効果が#%低下する",
    "engMod": "(T17) Players have #% less effect of Flasks applied to them",
    "value": "40",
    "type": "Prefix",
    "weight": 50,
    "tier": 2200,
    "engRegex": "sks",
    "Regex": "るフ",
    "tradeStatIds": [
      "explicit.stat_1207482628"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 47,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 0,
    "modTier17": true
  },
  "(T17) エリアの移動する呪印領域がパッチ状に存在し、ランダムな呪印を付与する": {
    "mod": "(T17) エリアの移動する呪印領域がパッチ状に存在し、ランダムな呪印を付与する",
    "engMod": "(T17) Area contains patches of moving Marked Ground, inflicting random Marks",
    "value": "",
    "type": "Suffix",
    "weight": 50,
    "tier": 1190,
    "engRegex": "ovi",
    "Regex": "し、ラ",
    "tradeStatIds": [
      "explicit.stat_2796704737"
    ],
    "map_item_drop_quantity_+%": 16,
    "map_item_drop_rarity_+%": 8,
    "map_pack_size_+%": 5,
    "map_map_item_drop_chance_+%_final_from_uber_mod": 0,
    "map_currency_drop_chance_+%_final_from_uber_mod": 0,
    "map_scarab_drop_chance_+%_final_from_uber_mod": 36,
    "modTier17": true
  }
};
