// Auto-generated by tools_poe2/extract_tablet_mods.py
const tabletModList = {
  "モンスターのエフェクティブが(##)%増加する": {
    "mod": "モンスターのエフェクティブが(##)%増加する",
    "engMod": "Monsters have (##)% increased Effectiveness",
    "value": "7-11",
    "type": "Prefix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_2065500219"
    ]
  },
  "マップで見つかるアイテムのレアリティが(##)%増加する": {
    "mod": "マップで見つかるアイテムのレアリティが(##)%増加する",
    "engMod": "(##)% increased Rarity of Items found in Map",
    "value": "18-30",
    "type": "Prefix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_2306002879"
    ]
  },
  "マップのパックサイズが(##)%増加する": {
    "mod": "マップのパックサイズが(##)%増加する",
    "engMod": "(##)% increased Pack Size in Map",
    "value": "6-10",
    "type": "Prefix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのマジックモンスターが(##)%増加する": {
    "mod": "マップのマジックモンスターが(##)%増加する",
    "engMod": "Map has (##)% increased Magic Monsters",
    "value": "50-70",
    "type": "Prefix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのレアモンスターの数が(##)%増加する": {
    "mod": "マップのレアモンスターの数が(##)%増加する",
    "engMod": "Map has (##)% increased number of Rare Monsters",
    "value": "25-40",
    "type": "Prefix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップで見つかるゴールドが(##)%増加する": {
    "mod": "マップで見つかるゴールドが(##)%増加する",
    "engMod": "(##)% increased Gold found in Map",
    "value": "25-40",
    "type": "Prefix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップでの獲得経験値が(##)%増加する": {
    "mod": "マップでの獲得経験値が(##)%増加する",
    "engMod": "(##)% increased Experience gain in Map",
    "value": "10-20",
    "type": "Prefix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_57434274"
    ]
  },
  "マップにレアのチェストが追加で(##)個出現する": {
    "mod": "マップにレアのチェストが追加で(##)個出現する",
    "engMod": "Map contains (##) additional Rare Chests",
    "value": "2-3",
    "type": "Prefix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップで見つかるウェイストーンの数量が(##)%増加する": {
    "mod": "マップで見つかるウェイストーンの数量が(##)%増加する",
    "engMod": "(##)% increased Quantity of Waystones found in Map",
    "value": "30-50",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_2777224821"
    ]
  },
  "マップのレアモンスターは(##)%の確率でモッドを追加で#個持つ": {
    "mod": "マップのレアモンスターは(##)%の確率でモッドを追加で#個持つ",
    "engMod": "Rare Monsters in Map have a (##)% chance to have an additional Modifier",
    "value": "50-80",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップにシュラインが出現する確率が(##)%増加する": {
    "mod": "マップにシュラインが出現する確率が(##)%増加する",
    "engMod": "Map has (##)% increased chance to contain Shrines",
    "value": "70-100",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_689816330"
    ]
  },
  "マップにシュラインが追加で#個出現する": {
    "mod": "マップにシュラインが追加で#個出現する",
    "engMod": "Map contains an additional Shrine",
    "value": "1|0|0",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップにストロングボックスが出現する確率が(##)%増加する": {
    "mod": "マップにストロングボックスが出現する確率が(##)%増加する",
    "engMod": "Map has (##)% increased chance to contain Strongboxes",
    "value": "70-100",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_4279535856"
    ]
  },
  "マップにストロングボックスが追加で#個出現する": {
    "mod": "マップにストロングボックスが追加で#個出現する",
    "engMod": "Map contains an additional Strongbox",
    "value": "1|0|0",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップにエッセンスが出現する確率が(##)%増加する": {
    "mod": "マップにエッセンスが出現する確率が(##)%増加する",
    "engMod": "Map has (##)% increased chance to contain Essences",
    "value": "70-100",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_1825943485"
    ]
  },
  "マップにエッセンスが追加で#個出現する": {
    "mod": "マップにエッセンスが追加で#個出現する",
    "engMod": "Map contains an additional Essence",
    "value": "1|0|0",
    "type": "Prefix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップにアズメリの精霊が出現する確率が(##)%増加する": {
    "mod": "マップにアズメリの精霊が出現する確率が(##)%増加する",
    "engMod": "Map has (##)% increased chance to contain Azmeri Spirits",
    "value": "70-100",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_3815617979"
    ]
  },
  "マップにアズメリの精霊が追加で#体出現する": {
    "mod": "マップにアズメリの精霊が追加で#体出現する",
    "engMod": "Map contains # additional Azmeri Spirit",
    "value": "1|0|0",
    "type": "Prefix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップにローグエグザイルが出現する確率が(##)%増加する": {
    "mod": "マップにローグエグザイルが出現する確率が(##)%増加する",
    "engMod": "Map has (##)% increased chance to contain Rogue Exiles",
    "value": "35-50",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_1352729973"
    ]
  },
  "マップにローグエグザイルが追加で#体生息している": {
    "mod": "マップにローグエグザイルが追加で#体生息している",
    "engMod": "Map is inhabited by # additional Rogue Exile",
    "value": "1|0|0",
    "type": "Prefix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップにサモ二ングサークルが追加で#個出現する": {
    "mod": "マップにサモ二ングサークルが追加で#個出現する",
    "engMod": "Map contains an additional Summoning Circle",
    "value": "1",
    "type": "Prefix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップにサモニングサークルが出現する確率が(##)%増加する": {
    "mod": "マップにサモニングサークルが出現する確率が(##)%増加する",
    "engMod": "Map has (##)% increased chance to contain a Summoning Circle",
    "value": "35-50",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップはランダムなモッドを追加で(##)個持つ": {
    "mod": "マップはランダムなモッドを追加で(##)個持つ",
    "engMod": "Map has (##) additional random Modifiers",
    "value": "1-2",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_588512487"
    ]
  },
  "ユニークモンスターはモッドを追加で#個持つ": {
    "mod": "ユニークモンスターはモッドを追加で#個持つ",
    "engMod": "Unique Monsters have # additional Rare Modifier",
    "value": "1",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_3371085671"
    ]
  },
  "マップのブリーチがスポーンするマジックモンスターが(##)%増加する": {
    "mod": "マップのブリーチがスポーンするマジックモンスターが(##)%増加する",
    "engMod": "Breaches in Map spawn (##)% increased Magic Monsters",
    "value": "40-70",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのブリーチはレアモンスターを追加で(##)体スポーンさせる": {
    "mod": "マップのブリーチはレアモンスターを追加で(##)体スポーンさせる",
    "engMod": "Breaches in Map spawn (##) additional Rare Monsters",
    "value": "1-2",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのブリーチはモンスター密度が(##)%増加する": {
    "mod": "マップのブリーチはモンスター密度が(##)%増加する",
    "engMod": "Breaches in Map have (##)% increased Monster density",
    "value": "5-10",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのブリーチが開閉する速度が(##)%速くなる|マップのブリーチはモンスター密度が(##)%増加する": {
    "mod": "マップのブリーチが開閉する速度が(##)%速くなる|マップのブリーチはモンスター密度が(##)%増加する",
    "engMod": "Breaches in Map open and close (##)% faster|Breaches in Map have (##)% increased Monster density",
    "value": "10-30|3-8",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "",
      ""
    ]
  },
  "マップのブリーチには握られた手が追加で(##)個出現する": {
    "mod": "マップのブリーチには握られた手が追加で(##)個出現する",
    "engMod": "Breaches in Map contain (##) additional Clasped Hands",
    "value": "1-3",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのブリーチモンスターがドロップするブリーチスプリンターの数量が(##)%増加する": {
    "mod": "マップのブリーチモンスターがドロップするブリーチスプリンターの数量が(##)%増加する",
    "engMod": "(##)% increased Quantity of Breach Splinters dropped by Breach Monsters in Map",
    "value": "15-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップは(##)%の確率でブリーチが追加で#個出現する": {
    "mod": "マップは(##)%の確率でブリーチが追加で#個出現する",
    "engMod": "Map has (##)% chance to contain an additional Breach",
    "value": "15-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップでモンスターがドロップするエクスペディションアーティファクトの数量が(##)%増加する": {
    "mod": "マップでモンスターがドロップするエクスペディションアーティファクトの数量が(##)%増加する",
    "engMod": "(##)% increased quantity of Expedition Artifacts dropped by Monsters in Map",
    "value": "15-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップでエクスペディションの爆発物の設置範囲が(##)%増加する": {
    "mod": "マップでエクスペディションの爆発物の設置範囲が(##)%増加する",
    "engMod": "(##)% increased Expedition Explosive Placement Range in Map",
    "value": "15-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのエクスペディションのレムナントが+(##)個される": {
    "mod": "マップのエクスペディションのレムナントが+(##)個される",
    "engMod": "Expeditions in Map have +(##) Remnants",
    "value": "1-2",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップでエクスペディションの爆発物の半径が(##)%増加する": {
    "mod": "マップでエクスペディションの爆発物の半径が(##)%増加する",
    "engMod": "(##)% increased Expedition Explosive Radius in Map",
    "value": "15-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップでルーニックモンスターがドロップするエクスペディションログブックの数量が(##)%増加する": {
    "mod": "マップでルーニックモンスターがドロップするエクスペディションログブックの数量が(##)%増加する",
    "engMod": "(##)% increased Quantity of Expedition Logbooks dropped by Runic Monsters in Map",
    "value": "15-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのレア エクスペディションモンスターの数が(##)%増加する": {
    "mod": "マップのレア エクスペディションモンスターの数が(##)%増加する",
    "engMod": "(##)% increased number of Rare Expedition Monsters in Map",
    "value": "25-40",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのエクスペディションのレムナントの効果が(##)%増加する": {
    "mod": "マップのエクスペディションのレムナントの効果が(##)%増加する",
    "engMod": "(##)% increased Effect of Expedition Remnants in Map",
    "value": "12-18",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップに出現するルーニックモンスターマーカーの数が(##)%増加する": {
    "mod": "マップに出現するルーニックモンスターマーカーの数が(##)%増加する",
    "engMod": "Map contains (##)% increased number of Runic Monster Markers",
    "value": "15-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップで見つかるシミュラクラムスプリンターのスタックサイズが(##)%増加する": {
    "mod": "マップで見つかるシミュラクラムスプリンターのスタックサイズが(##)%増加する",
    "engMod": "(##)% increased Stack size of Simulacrum Splinters found in Map",
    "value": "15-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_3836551197"
    ]
  },
  "マップでデリリウムの霧は消失する前に追加で(##)秒持続する": {
    "mod": "マップでデリリウムの霧は消失する前に追加で(##)秒持続する",
    "engMod": "Delirium Fog in Map lasts (##) additional seconds before dissipating",
    "value": "6-12",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップでデリリウムの霧は(##)%遅く消失する": {
    "mod": "マップでデリリウムの霧は(##)%遅く消失する",
    "engMod": "Delirium Fog in Map dissipates (##)% slower",
    "value": "-30--20",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのデリリウムのせん妄度は鏡から離れるほど(##)%速く増える": {
    "mod": "マップのデリリウムのせん妄度は鏡から離れるほど(##)%速く増える",
    "engMod": "Delirium in Map increases (##)% faster with distance from the mirror",
    "value": "15-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのデリリウムモンスターはパックサイズが(##)%増加する": {
    "mod": "マップのデリリウムモンスターはパックサイズが(##)%増加する",
    "engMod": "Delirium Monsters in Map have (##)% increased Pack Size",
    "value": "15-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのデリリウムの霧がスポーンさせる割れる鏡の数が(##)%増加する": {
    "mod": "マップのデリリウムの霧がスポーンさせる割れる鏡の数が(##)%増加する",
    "engMod": "Delirium Fog in Map spawns (##)% increased Fracturing Mirrors",
    "value": "15-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップでレアモンスターを倒すとデリリウムの鏡のタイマーが(##)秒停止する": {
    "mod": "マップでレアモンスターを倒すとデリリウムの鏡のタイマーが(##)秒停止する",
    "engMod": "Slaying Rare Monsters in Map pauses the Delirium Mirror Timer for (##) seconds",
    "value": "3-5",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのデリリウムエンカウンターでユニークボスがスポーンする確率が(##)%高くなる": {
    "mod": "マップのデリリウムエンカウンターでユニークボスがスポーンする確率が(##)%高くなる",
    "engMod": "Delirium Encounters in Map are (##)% more likely to spawn Unique Bosses",
    "value": "15-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのリチュアルの祭壇で捧げられたモンスターが付与するトリビュートが(##)%増加する": {
    "mod": "マップのリチュアルの祭壇で捧げられたモンスターが付与するトリビュートが(##)%増加する",
    "engMod": "Monsters Sacrificed at Ritual Altars in Map grant (##)% increased Tribute",
    "value": "18-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのリチュアルの祭壇で恩寵のリロールでコストとして消費するトリビュートが(##)%減少する": {
    "mod": "マップのリチュアルの祭壇で恩寵のリロールでコストとして消費するトリビュートが(##)%減少する",
    "engMod": "Rerolling Favours at Ritual Altars in Map costs (##)% reduced Tribute",
    "value": "20-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのリチュアルの祭壇での恩寵の繰り越しにコストとしてかかるトリビュートが(##)%減少する": {
    "mod": "マップのリチュアルの祭壇での恩寵の繰り越しにコストとしてかかるトリビュートが(##)%減少する",
    "engMod": "Deferring Favours at Ritual Altars in Map costs (##)% reduced Tribute",
    "value": "20-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのリチュアルの祭壇で繰り越しした恩寵は(##)%速く再出現する": {
    "mod": "マップのリチュアルの祭壇で繰り越しした恩寵は(##)%速く再出現する",
    "engMod": "Favours Deferred at Ritual Altars in Map reappear (##)% sooner",
    "value": "25-40",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのリチュアルの祭壇は恩寵を追加で(##)回リロールできる": {
    "mod": "マップのリチュアルの祭壇は恩寵を追加で(##)回リロールできる",
    "engMod": "Ritual Altars in Map allow rerolling Favours (##) additional times",
    "value": "1-3",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのリチュアルの祭壇で恩寵のリロールは(##)%の確率でトリビュートをコストとして消費しない": {
    "mod": "マップのリチュアルの祭壇で恩寵のリロールは(##)%の確率でトリビュートをコストとして消費しない",
    "engMod": "Favours Rerolled at Ritual Altars in Map have (##)% chance to cost no Tribute",
    "value": "300-600",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのリチュアルの祭壇で復活するモンスターがマジックになる確率が(##)%増加する": {
    "mod": "マップのリチュアルの祭壇で復活するモンスターがマジックになる確率が(##)%増加する",
    "engMod": "Revived Monsters from Ritual Altars in Map have (##)% increased chance to be Magic",
    "value": "35-70",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのリチュアルの祭壇で復活するモンスターがレアになる確率が(##)%増加する": {
    "mod": "マップのリチュアルの祭壇で復活するモンスターがレアになる確率が(##)%増加する",
    "engMod": "Revived Monsters from Ritual Altars in Map have (##)% increased chance to be Rare",
    "value": "25-40",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのリチュアルの恩寵がお告げとなる確率が(##)%増加する": {
    "mod": "マップのリチュアルの恩寵がお告げとなる確率が(##)%増加する",
    "engMod": "Ritual Favours in Map have (##)% increased chance to be Omens",
    "value": "35-70",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップにストロングボックスが追加で(##)個出現する": {
    "mod": "マップにストロングボックスが追加で(##)個出現する",
    "engMod": "Map contains (##) additional Strongboxes",
    "value": "1-2",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップにシュラインが追加で(##)個出現する": {
    "mod": "マップにシュラインが追加で(##)個出現する",
    "engMod": "Map contains (##) additional Shrines",
    "value": "1-2",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップにエッセンスが追加で(##)個出現する": {
    "mod": "マップにエッセンスが追加で(##)個出現する",
    "engMod": "Map contains (##) additional Essences",
    "value": "1-2",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップにアズメリの精霊が追加で(##)体出現する": {
    "mod": "マップにアズメリの精霊が追加で(##)体出現する",
    "engMod": "Map contains (##) additional Azmeri Spirits",
    "value": "1-2",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップボスがドロップするウェイストーンの数量が(##)%増加する": {
    "mod": "マップボスがドロップするウェイストーンの数量が(##)%増加する",
    "engMod": "(##)% increased Quantity of Waystones dropped by Map Bosses",
    "value": "18-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_1457896329"
    ]
  },
  "マップボスが付与する経験値が(##)%上昇する": {
    "mod": "マップボスが付与する経験値が(##)%上昇する",
    "engMod": "Map Bosses grant (##)% increased Experience",
    "value": "40-80",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_3860150265"
    ]
  },
  "マップボスのドロップするアイテムのレアリティが(##)%増加する": {
    "mod": "マップボスのドロップするアイテムのレアリティが(##)%増加する",
    "engMod": "(##)% increased Rarity of Items dropped by Map Bosses",
    "value": "35-60",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_4255069232"
    ]
  },
  "マップボスのドロップするアイテムの数量が(##)%増加する": {
    "mod": "マップボスのドロップするアイテムの数量が(##)%増加する",
    "engMod": "(##)% increased Quantity of Items dropped by Map Bosses",
    "value": "13-20",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_3119172063"
    ]
  },
  "マップのアビスがスポーンするモンスターの数が(##)%増加する": {
    "mod": "マップのアビスがスポーンするモンスターの数が(##)%増加する",
    "engMod": "Abysses in Map spawn (##)% increased Monsters",
    "value": "20-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_944630113"
    ]
  },
  "マップのアビスの穴からレアモンスターが追加で(##)体スポーンする": {
    "mod": "マップのアビスの穴からレアモンスターが追加で(##)体スポーンする",
    "engMod": "(##) additional Rare Monsters are spawned from Abysses in Map",
    "value": "1-2",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのアビサルモンスターの難易度および報酬が閉じた穴の数ごとに増加する": {
    "mod": "マップのアビサルモンスターの難易度および報酬が閉じた穴の数ごとに増加する",
    "engMod": "Abyssal Monsters in Map have increased Difficulty and Reward for each closed Pit",
    "value": "1",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのアビスがアビスの深淵に繋がる確率が(##)%増加する": {
    "mod": "マップのアビスがアビスの深淵に繋がる確率が(##)%増加する",
    "engMod": "Abysses in Map have (##)% increased chance to lead to an Abyssal Depths",
    "value": "10-20",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_2722831300"
    ]
  },
  "マップにアビスが追加で#個出現する": {
    "mod": "マップにアビスが追加で#個出現する",
    "engMod": "Map contains an additional Abyss",
    "value": "1",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのアビスの穴が報酬を持つ確率が#倍になる": {
    "mod": "マップのアビスの穴が報酬を持つ確率が#倍になる",
    "engMod": "Abyss Pits in Map are twice as likely to have Rewards",
    "value": "-50",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップに(##)%の確率でアビスが追加で#個出現する": {
    "mod": "マップに(##)%の確率でアビスが追加で#個出現する",
    "engMod": "Map has (##)% chance to contain four additional Abysses",
    "value": "20-40",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  },
  "マップのアビサルモンスターがアビサルモッドを持つ確率が(##)%増加する": {
    "mod": "マップのアビサルモンスターがアビサルモッドを持つ確率が(##)%増加する",
    "engMod": "(##)% increased chance for Abyssal monsters in Map to have Abyssal Modifiers",
    "value": "20-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      "explicit.stat_2789248444"
    ]
  },
  "マップのアビスから冒涜カレンシーを獲得する確率が(##)%増加する": {
    "mod": "マップのアビスから冒涜カレンシーを獲得する確率が(##)%増加する",
    "engMod": "(##)% increased chance for Desecrated Currency from Abysses in Map",
    "value": "20-30",
    "type": "Suffix",
    "tier": 0,
    "engRegex": "",
    "Regex": "",
    "tradeStatIds": [
      ""
    ]
  }
};
